### ISSUE TITLE
Atmega328p UART/USART

### ISSUE THREAD

**Issue by Mshivam2409** [Mshivam2409/rustduino#29]
- [ ] Figure out the implementation of USART/UART
- [ ] Create a readme.md in `atmega328p/com/readme.md` with generic function definitions for implementing USART/UART

**You are not supposed to write any rust file in this issue**

**Comment by richa1711** [comment]
commented!

**Comment by kshitijk20** [comment]
I want to take this issue!

**Comment by Mshivam2409** [comment]
@kshitijk20  A single person commenting should be enough for the team. Please name your team members in the first comment.

**Comment by sanmatip20** [comment]
I and my teammates Akshit Verma and Samarth Tripathi would like to take this issue.
