### ISSUE TITLE
Atmega2560p USART/UART Implementation

### ISSUE THREAD

**Issue by Mshivam2409** [Mshivam2409/rustduino#32]
- [ ] Figure out the implementation of USART/UART
- [x] Create a readme.md in `atmega2560p/com/readme.md` with generic function definitions for implementing USART/UART

**You are not supposed to write any rust file in this issue**

**Comment by dkjha20** [comment]
Our sub-team would like to do this issue. RD2B
Devansh, Nikhil, Satender, Aniket
As we have already discussed about it I am myself assigning the tasks.
Thank you for publishing the issue :)
