### ISSUE TITLE
Atmega2560p I2C Implementation

### ISSUE THREAD

**Issue by Mshivam2409** [Mshivam2409/rustduino#35]
- [ ] Figure out the implementation of I2C
- [ ] Create a readme.md in `atmega2560p/com/readme.md` with generic function definitions for implementing I2C

**You are not supposed to write any rust file in this issue**

**Comment by tulikashukla** [comment]
Our sub-team would like to take up this issue.
Team members: Tulika Shukla, Prateek Kumar Pandey, Sahil
Thank you.

**Comment by Mshivam2409** [comment]
Closed with #68
