### ISSUE TITLE
Shift Registers

### ISSUE THREAD

**Issue by Mshivam2409** [Mshivam2409/rustduino#53]
- [x] Read and implement SN74HC164 8 bit shift register using digital pins. Please note that implementation must be generic i.e. please use `core::hal` instead of `core::atmega328p::hal` by using features. Make necessary changes in the code for the names to be the same and remember to discuss with the other team.
- [ ] Write an example.

**Comment by sanmatip20** [comment]
Sanmati, Akshit, Samarth would be working on this issue.

**Comment by Mshivam2409** [comment]
Closed with #30
