### ISSUE TITLE
7 Segment Display

### ISSUE THREAD

**Issue by Mshivam2409** [Mshivam2409/rustduino#54]
- [x] Read and implement 7 segment display using digital pins. Please note that implementation must be generic i.e. please use `core::hal` instead of `core::atmega328p::hal` by using features. Make necessary changes in the code for the names to be the same and remember to discuss with the other team.
- [x] Write an example.

**Comment by dkjha20** [comment]
As our team has finalized HAL and the code is pretty same with HAL of atmega328p we ( sub team B team atmega 2560p ) would like to work on this. I think we can discuss the necessary changes in code for uniformity in HAL with "sub team B team atmega 328p" which would be working on issue #53 SN74HC164 8 bit shift registers as pointed out.
CC - @nikhilg2121 @3007-Ani-Sha @Libra-SKY

**Comment by tulikashukla** [comment]
Our team will take up this issue.
Team members: Tulika, Sahil, Prateek

**Comment by Mshivam2409** [comment]
Closed with #68
