### ISSUE TITLE
Random Number Generator 

### ISSUE THREAD

**Issue by Mshivam2409** [Mshivam2409/rustduino#55]
- [x] Implement Part A of the Random Number Generator paper after #56  : https://gist.github.com/bloc97/b55f684d17edd8f50df8e918cbc00f94 
- [x] Implement Part B after #45 is complete.

**Comment by dkjha20** [comment]
I would like to take this and I hope I would complete it before the End-Term evaluation. I would be doing it along the crates.io/documentation work :)
