### ISSUE TITLE
Analog IC

### ISSUE THREAD

**Issue by Mshivam2409** [Mshivam2409/rustduino#56]
- [x] Implement `analogRead` 
- [x] Implement `analogWrite`
- [x] Implement `analogReference`

**Comment by dkjha20** [comment]
I think this issue would be taken by all USART team members.
Me, Nikhil, Satender, Aniket, Ayush, Saurabh, Ksitij and Richa :)

**Comment by Mshivam2409** [comment]
Closed with #68
